server:
  servlet:
    context-path: /auth-backup
  port: 20002

#日志配置
logging:
  config: classpath:logback.xml

# backup datasource
spring:
  application:
    name: auth-backup
  boot:
    admin:
      client:
        url: "http://localhost:8000"
  backup:
    datasource:
      host: localhost
      userName: root
      password: root
      database: cloud-auth
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        serviceName: ${spring.application.name}    # 注册到consul的服务名称
# 开放健康检查接口
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS