server:
  port: 8080

#日志配置
logging:
  config: classpath:logback.xml

# backup datasource
spring:
  application:
    name: auth-backup
  boot:
    admin:
      client:
        url: "http://localhost:8000"
  backup:
    datasource:
      host: localhost
      userName: root
      password: root
      database: cloud-auth