server:
  port: 8088

#日志配置
logging:
  config: classpath:logback.xml
  level:
    cn.stt.cloud.auth..mapper: debug

mybatis:
  mapper-locations: classpath:sqlmap/*.xml
  type-aliases-package: cn.stt.cloud.auth.entity
  configuration:
    map-underscore-to-camel-case: true

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check

spring:
  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud_auth?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root